apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test_backstage
  annotations:
    github.com/project-slug: Catalin4513/test_backstage
spec:
  type: other
  lifecycle: unknown
  owner: my-group
  catalog:
  rules:
    - allow:
        - kind: Template
