apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: example-service-template
  description: "A template for creating example services"
  tags:
    - template
spec:
  type: service
  owner: team-example
  path: "./templates/example-service-template"
  parameters:
    - title: "Service Name"
      description: "Name of the service"
      type: string
      required: true
    - title: "Service Description"
      description: "A brief description of the service"
      type: string
      required: false
  steps:
    - name: "generate-service"
      action: "backstage.io/generate"
      input:
        templatePath: "./templates/example-service"
