metadata:
  annotations:
    backstage.io/managed-by-location: >-
      url:https://github.com/Catalin4513/test_backstage/tree/main/composition-example.yaml
    backstage.io/managed-by-origin-location: >-
      url:https://github.com/Catalin4513/test_backstage/blob/main/composition-example.yaml
    backstage.io/view-url: >-
      https://github.com/Catalin4513/test_backstage/tree/main/composition-example.yaml
    backstage.io/edit-url: >-
      https://github.com/Catalin4513/test_backstage/edit/main/composition-example.yaml
    backstage.io/source-location: url:https://github.com/Catalin4513/test_backstage/tree/main/
  namespace: default
  name: my-resource-name
  description: A brief description of the resource
  uid: 9cd68631-c2a7-497b-bd7a-3f2364d22c00
  etag: 98c2871078aec7fed2d0ddd8eae0363960711e57
apiVersion: backstage.io/v1alpha1
kind: Resource
spec:
  type: service
  owner: guest
  compositeTypeRef:
    apiVersion: aws.platform.upbound.io/v1alpha1
    kind: XKarpenter
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: storage-bucket
            base:
              apiVersion: s3.aws.upbound.io/v1beta2
              kind: BucketIntelligentTieringConfiguration
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: path/to/source12
                toFieldPath: path/to/target14
              - type: FromCompositeFieldPath
                fromFieldPath: path/to/source2
                toFieldPath: path/to/target2
                transforms:
                - type: convert
                  convert:
                    toType: string
                - type: map
                  map:
                    us: us-east-2
                    eu: eu-north-1
          - name: network-subnet
            base:
              apiVersion: s3.aws.upbound.io/v1beta2
              kind: BucketReplicationConfiguration
            patches:
              - type: ToCompositeFieldPath
                fromFieldPath: path/to/source3
                toFieldPath: path/to/target3
                transforms:
                - type: map
                  map:
                    "field1-text": "firstField"
                    "field2-text": "secondField"
