apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  description: "An example service"
  tags:
    - service
spec:
  type: service
  lifecycle: production
  owner: team-example
  consumesApis:
    - example-api
  providesApis:
    - example-api
