apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: my-example-resource
  description: "This is an example resource for a demo"
  labels:
    example: true
spec:
  type: service
  owner: team-example
  lifecycle: production
  ownerRefs:
    - apiVersion: backstage.io/v1alpha1
      kind: Group
      name: team-example
  system: my-example-system
  uri: "https://example.com/resource"
