apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gfhfdgdfg
  description: Crossplane Composition
  annotations:
    backstage.io/edit-url: /composition-editor/edit/gfhfdgdfg
spec:
  type: Composition
  owner: Catalin4513
