apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: werwerwe
  description: Crossplane Composition
  annotations:
    backstage.io/edit-url: /composition-editor/edit/
spec:
  type: Composition
  owner: Catalin4513
  compositeTypeRef:
    apiVersion: rrrrrrrrrrrrrrr
    kind: ttttttttttttttttt
  
