apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fweew
  description: Crossplane Composition
  annotations:
    backstage.io/edit-url: /composition-editor/edit/
spec:
  type: Composition
  owner: Catalin4513
  compositeTypeRef:
    apiVersion: werew
    kind: werwe
  
