apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: 
  annotations:
    meta.crossplane.io/source: github.com/crossplane/crossplane
    meta.crossplane.io/license: Apache-2.0
    guide: quickstart
